update get-lit scripts
luvit/lit pull request #282
Opened 2021-02-17 20:27 UTC by truemedian

2021-06-24 21:10 UTC, SinisterRectus approved these changes
Not sure why this was never accepted. Looks fine here.

2021-06-25 21:17 UTC, creationix commented
I think I'm done moving things around, the latest version should be:

- luvi @ 2.12.0
- lit @ 3.8.4
- luvit @ 2.18.0

The Luvit release is pending review of this PR https://github.com/luvit/luvit/pull/1142

2021-06-25 21:22 UTC, creationix requested changes

2021-06-25 21:22 UTC, creationix commented on get-lit.ps1
> +$LIT_VERSION = "3.8.2"
Update to `"3.8.4"

2021-06-25 21:22 UTC, creationix commented on get-lit.sh
> +LIT_VERSION=${LIT_VERSION:-3.8.2}
Update to `"3.8.4"`

2021-06-25 21:46 UTC, creationix approved these changes

2021-06-25 21:46 UTC, merged